package com.qiao.brew.db;

import com.qiao.brew.data.*;
import com.qiao.ga.EvoSQL;
import com.qiao.ga.PathResult;
import com.qiao.spring.pojo.Table;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;
import com.qiao.brew.data.*;

import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;

/**
 * 从数据库中获取 test fixture（测试定位装置？）
 * A class for obtaining test fixtures from a database, using the
 * EvoSQL algorithm from the GA package.
 */
public class EvoSQLRunner implements QueryRunner {

    /**
     * The EvoSQL class factory used.
     */
    @Getter
    @Setter
    @NonNull
    private EvoSQLFactory evoSQLFactory = new EvoSQLFactory();

    /**
     * Returns test data fixtures for the given SQL query, as
     * generated by the EvoSQL algorithm.
     *
     * @param sqlQuery       The SQL query to generate fixtures for.
     * @param tables The schema
     * @return A list of fixtures for the given SQL query,
     * generated by the EvoSQL algorithm.
     */
    @Override
    public Result runQuery(@NonNull String sqlQuery, Table[] tables, List<String> coveragePaths) {
        EvoSQL evoSQL = new EvoSQL(false);
        com.qiao.ga.Result evoSQLResult = evoSQL.execute(sqlQuery, tables, coveragePaths);
        return convertResult(evoSQLResult);
    }

    Result convertResult(com.qiao.ga.Result evoSqlResult) {
        return new Result(
                evoSqlResult.getInputQuery(),
                evoSqlResult.getPathResults().stream()
                        .filter(pr -> pr.getFixture() != null)
                        .filter(PathResult::isSuccess)
                        .map(this::convertPathResult)
                        .collect(Collectors.toList())
        );
    }

    private Path convertPathResult(PathResult pathResult) {
        return new Path(
                convertFixture(pathResult.getFixture()),
                pathResult.getPathSql(),
                pathResult.getPathNo(),
                pathResult.isProductionSuccess(),
                pathResult.getProductionOutput()
        );
    }

    private Fixture convertFixture(com.qiao.ga.fixture.Fixture evoSqlFixture) {
        return new Fixture(
                evoSqlFixture.getTables().stream().map(this::convertFixtureTable).collect(Collectors.toList())
        );
    }

    private FixtureTable convertFixtureTable(com.qiao.ga.fixture.FixtureTable fixtureTable) {
        final TableSchema schema = convertTableSchema(fixtureTable.getSchema());
        return new FixtureTable(
                schema,
                fixtureTable.getRows().stream().map(r -> convertFixtureRow(r, schema)).collect(Collectors.toList())
        );
    }

    private TableSchema convertTableSchema(com.qiao.ga.sql.TableSchema tableSchema) {
        return new TableSchema(
                tableSchema.getName(),
                tableSchema.getColumns().stream()
                        .map(c -> new FixtureColumn(c.getName(), c.getType().getTypeString()))
                        .collect(Collectors.toList())
        );
    }

    private FixtureRow convertFixtureRow(com.qiao.ga.fixture.FixtureRow fixtureRow, TableSchema schema) {
        return new FixtureRow(
                new HashMap<>(fixtureRow.getValues()),
                schema
        );
    }
}
