server:
  port: 8080
spring:
  application:
    name: sqlexercise
  datasource:
    url: jdbc:mysql://localhost:3306/sqlexercise?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    #        url: jdbc:mysql://172.29.4.28:3306/sqlexercise?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
    #        password: aptx4869
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    connect-timeout: 30
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml

# 以下为本项目自定义配置项
sqlexercise:
  # 数据库容器相关配置
  database:
    mysql:
      need: true  # 表示是否运行时需要启动，下同
      recreate: false  # 表示每次启动时是否需要重新创建，下同
    oceanbase:
      need: true
      recreate: false
      # 题目中使用的app_user表的个数
      table-duplicate-num: 15
  # 运行docker的主机和端口
  docker:
#    host: localhost
    host: 172.29.4.60
    port: 2375